from pathlib import Path

TEMPLATE = '''\
"""
gaptrace_pipeline.py — generated by gaptrace-capture init

Fill in each stage with your pipeline's function calls.
Capture calls are pre-positioned. Do not move them.
"""

import gaptrace_capture  # noqa: F401  (install: pip install gaptrace-capture)

def run_pipeline(query: str) -> str:

    cap = gaptrace_capture.start(query=query, pipeline="my_project")

    # --- Stage 1: Retrieval ---
    # chunks = your_retriever.retrieve(query)
    # cap.chunks(chunks)

    # --- Stage 2: Context assembly ---
    # prompt, budget = your_assembler.assemble(chunks, history)
    # cap.context(prompt, budget)

    # --- Stage 3: History management ---
    # cap.history(pre=history_before, post=history_after, eviction_reason="token_budget")

    # --- Stage 4: LLM call ---
    # response = your_llm_client.call(prompt)
    # run_id = cap.response(response)   # auto-commits; run_id is "sNrN"
    # print(f"Captured {run_id} — try: gaptrace explain {run_id}")

    # cap.commit() is called automatically inside cap.response()
    # call it explicitly here only if you skip cap.response()
    # cap.commit()

    return response  # noqa: F821
'''


def generate_scaffold(output_path: Path | None = None) -> Path:
    if output_path is None:
        output_path = Path.cwd()
    target = output_path / "gaptrace_pipeline.py"
    if target.exists():
        raise FileExistsError(
            f"{target} already exists. Remove it first if you want to regenerate."
        )
    target.write_text(TEMPLATE, encoding="utf-8")
    return target
